layout_spectrum: 0.6845878
typography_spectrum: 0.2724014
color:
  saturation: 0.5215054
  brandStrength: 1
  lightness: 0.5107527
  brandColors:
    - '#000000'
    - '#CFCFCF'
    - '#4B4B4B'
  rhythmicContrast: 0.5519713
name: Krasi Stoichkov
