collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.2670251
color:
  saturation: 0.7956989
  brandStrength: 1
  lightness: 0.1863799
  brandColors:
    - '#0C0D0F'
    - '#99B8E7'
    - '#4E4E4C'
    - '#C8E3FE'
    - '#E5AD78'
  rhythmicContrast: 1
layout_spectrum: 0.734767
name: Krasi Stoichkov
